version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      nuget-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/unrealpluginmanager.client/"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
