name: UnrealPluginManager

services:
  web-backend:
    image: retroandchill/unreal-plugin-manager:latest
    ports:
      - "8080:8080"
      - "8081:8081"
  
  postgresql:
    container_name: postgres
    image: postgres
    environment:
      PGDATA: /data/postgres
      POSTGRES_DB: postgres
    env_file:
      - "postgres.env"
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db: