/* tslint:disable */
/* eslint-disable */
//@ts-nocheck
/**
 * UnrealPluginManager.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents an overview of binary files for a specific platform and engine version.
 * @export
 * @interface BinariesOverview
 */
export interface BinariesOverview {
    /**
     * Gets or sets the unique identifier for the binary file.
     * @type {string}
     * @memberof BinariesOverview
     */
    id: string;
    /**
     * Gets or sets the target platform for which the binary is intended.
     * @type {string}
     * @memberof BinariesOverview
     */
    platform: string;
    /**
     * Gets or sets the engine version associated with the binary file or plugin.
     * @type {string}
     * @memberof BinariesOverview
     */
    engineVersion: string;
}

/**
 * Check if a given object implements the BinariesOverview interface.
 */
export function instanceOfBinariesOverview(value: object): value is BinariesOverview {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('engineVersion' in value) || value['engineVersion'] === undefined) return false;
    return true;
}

export function BinariesOverviewFromJSON(json: any): BinariesOverview {
    return BinariesOverviewFromJSONTyped(json, false);
}

export function BinariesOverviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): BinariesOverview {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'platform': json['platform'],
        'engineVersion': json['engineVersion'],
    };
}

export function BinariesOverviewToJSON(json: any): BinariesOverview {
    return BinariesOverviewToJSONTyped(json, false);
}

export function BinariesOverviewToJSONTyped(value?: BinariesOverview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'platform': value['platform'],
        'engineVersion': value['engineVersion'],
    };
}

