/* tslint:disable */
/* eslint-disable */
/**
 * UnrealPluginManager.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Conflict } from './Conflict';
import {
    ConflictFromJSON,
    ConflictFromJSONTyped,
    ConflictToJSON,
    ConflictToJSONTyped,
} from './Conflict';
import type { ResolutionResult } from './ResolutionResult';
import {
    ResolutionResultFromJSON,
    ResolutionResultFromJSONTyped,
    ResolutionResultToJSON,
    ResolutionResultToJSONTyped,
} from './ResolutionResult';

/**
 * Represents resolution failure due to detected conflicts among plugin dependencies within the Unreal Plugin Manager.
 * @export
 * @interface ConflictDetected
 */
export interface ConflictDetected extends ResolutionResult {
    /**
     * Gets or sets the list of conflicts detected during the dependency resolution process in the Unreal Plugin Manager.
     * @type {Array<Conflict>}
     * @memberof ConflictDetected
     */
    conflicts: Array<Conflict>;
    /**
     * 
     * @type {string}
     * @memberof ConflictDetected
     */
    readonly type: string;
}

/**
 * Check if a given object implements the ConflictDetected interface.
 */
export function instanceOfConflictDetected(value: object): value is ConflictDetected {
    if (!('conflicts' in value) || value['conflicts'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ConflictDetectedFromJSON(json: any): ConflictDetected {
    return ConflictDetectedFromJSONTyped(json, false);
}

export function ConflictDetectedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConflictDetected {
    if (json == null) {
        return json;
    }
    return {
        ...ResolutionResultFromJSONTyped(json, true),
        'conflicts': ((json['conflicts'] as Array<any>).map(ConflictFromJSON)),
        'type': json['type'],
    };
}

export function ConflictDetectedToJSON(json: any): ConflictDetected {
    return ConflictDetectedToJSONTyped(json, false);
}

export function ConflictDetectedToJSONTyped(value?: Omit<ConflictDetected, 'type'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...ResolutionResultToJSONTyped(value, true),
        'conflicts': ((value['conflicts'] as Array<any>).map(ConflictToJSON)),
    };
}

