/* tslint:disable */
/* eslint-disable */
//@ts-nocheck
/**
 * Unreal Plugin Manager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MetadataIdentifier
 */
export interface MetadataIdentifier {
  /**
   *
   * @type {string}
   * @memberof MetadataIdentifier
   */
  value?: string;
}

/**
 * Check if a given object implements the MetadataIdentifier interface.
 */
export function instanceOfMetadataIdentifier(value: object): value is MetadataIdentifier {
  return true;
}

export function MetadataIdentifierFromJSON(json: any): MetadataIdentifier {
  return MetadataIdentifierFromJSONTyped(json, false);
}

export function MetadataIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataIdentifier {
  if (json == null) {
    return json;
  }
  return {

    'value': json['value'] == null ? undefined : json['value'],
  };
}

export function MetadataIdentifierToJSON(json: any): MetadataIdentifier {
  return MetadataIdentifierToJSONTyped(json, false);
}

export function MetadataIdentifierToJSONTyped(value?: MetadataIdentifier | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {

    'value': value['value'],
  };
}

