/* tslint:disable */
/* eslint-disable */
/**
 * UnrealPluginManager.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PluginOverview } from './PluginOverview';
import {
    PluginOverviewFromJSON,
    PluginOverviewFromJSONTyped,
    PluginOverviewToJSON,
    PluginOverviewToJSONTyped,
} from './PluginOverview';

/**
 * Represents the output of a paged query of PluginOverview.
 * @export
 * @interface PluginOverviewPage
 */
export interface PluginOverviewPage {
    /**
     * The current page number of the result set.
     * @type {number}
     * @memberof PluginOverviewPage
     */
    pageNumber: number;
    /**
     * The total number of pages in the result set.
     * @type {number}
     * @memberof PluginOverviewPage
     */
    totalPages: number;
    /**
     * The number of items on each page.
     * @type {number}
     * @memberof PluginOverviewPage
     */
    pageSize: number;
    /**
     * The total number of items available in the result set.
     * @type {number}
     * @memberof PluginOverviewPage
     */
    count: number;
    /**
     * An array of items on the current page.
     * @type {Array<PluginOverview>}
     * @memberof PluginOverviewPage
     */
    items: Array<PluginOverview>;
}

/**
 * Check if a given object implements the PluginOverviewPage interface.
 */
export function instanceOfPluginOverviewPage(value: object): value is PluginOverviewPage {
    if (!('pageNumber' in value) || value['pageNumber'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PluginOverviewPageFromJSON(json: any): PluginOverviewPage {
    return PluginOverviewPageFromJSONTyped(json, false);
}

export function PluginOverviewPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginOverviewPage {
    if (json == null) {
        return json;
    }
    return {
        
        'pageNumber': json['pageNumber'],
        'totalPages': json['totalPages'],
        'pageSize': json['pageSize'],
        'count': json['count'],
        'items': ((json['items'] as Array<any>).map(PluginOverviewFromJSON)),
    };
}

export function PluginOverviewPageToJSON(json: any): PluginOverviewPage {
    return PluginOverviewPageToJSONTyped(json, false);
}

export function PluginOverviewPageToJSONTyped(value?: PluginOverviewPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pageNumber': value['pageNumber'],
        'totalPages': value['totalPages'],
        'pageSize': value['pageSize'],
        'count': value['count'],
        'items': ((value['items'] as Array<any>).map(PluginOverviewToJSON)),
    };
}

