/* tslint:disable */
/* eslint-disable */
/**
 * UnrealPluginManager.Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a requirement for a plugin, specifying the source of the requirement
 * and the version range that satisfies it.
 * @export
 * @interface PluginRequirement
 */
export interface PluginRequirement {
    /**
     * 
     * @type {string}
     * @memberof PluginRequirement
     */
    requiredBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PluginRequirement
     */
    requiredVersion?: string | null;
}

/**
 * Check if a given object implements the PluginRequirement interface.
 */
export function instanceOfPluginRequirement(value: object): value is PluginRequirement {
    return true;
}

export function PluginRequirementFromJSON(json: any): PluginRequirement {
    return PluginRequirementFromJSONTyped(json, false);
}

export function PluginRequirementFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginRequirement {
    if (json == null) {
        return json;
    }
    return {
        
        'requiredBy': json['requiredBy'] == null ? undefined : json['requiredBy'],
        'requiredVersion': json['requiredVersion'] == null ? undefined : json['requiredVersion'],
    };
}

export function PluginRequirementToJSON(json: any): PluginRequirement {
    return PluginRequirementToJSONTyped(json, false);
}

export function PluginRequirementToJSONTyped(value?: PluginRequirement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requiredBy': value['requiredBy'],
        'requiredVersion': value['requiredVersion'],
    };
}

