/* tslint:disable */
/* eslint-disable */
//@ts-nocheck
/**
 * Unreal Plugin Manager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents the identifiers for a plugin, including a globally unique identifier (GUID) and its corresponding name.
 * @export
 * @interface PluginIdentifiers
 */
export interface PluginIdentifiers {
    /**
     * The globally unique identifier (GUID) of the plugin.
     * @type {string}
     * @memberof PluginIdentifiers
     */
    id?: string;
    /**
     * The name of the plugin.
     * @type {string}
     * @memberof PluginIdentifiers
     */
    name?: string;
}

/**
 * Check if a given object implements the PluginIdentifiers interface.
 */
export function instanceOfPluginIdentifiers(value: object): value is PluginIdentifiers {
    return true;
}

export function PluginIdentifiersFromJSON(json: any): PluginIdentifiers {
    return PluginIdentifiersFromJSONTyped(json, false);
}

export function PluginIdentifiersFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginIdentifiers {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function PluginIdentifiersToJSON(json: any): PluginIdentifiers {
    return PluginIdentifiersToJSONTyped(json, false);
}

export function PluginIdentifiersToJSONTyped(value?: PluginIdentifiers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

