/* tslint:disable */
/* eslint-disable */
//@ts-nocheck
/**
 * Unreal Plugin Manager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {BigInteger} from './BigInteger';
import {BigIntegerFromJSON, BigIntegerToJSON,} from './BigInteger';

/**
 *
 * @export
 * @interface PrereleaseIdentifier
 */
export interface PrereleaseIdentifier {
  /**
   *
   * @type {string}
   * @memberof PrereleaseIdentifier
   */
  value?: string;
  /**
   *
   * @type {BigInteger}
   * @memberof PrereleaseIdentifier
   */
  numericValue?: BigInteger;
}

/**
 * Check if a given object implements the PrereleaseIdentifier interface.
 */
export function instanceOfPrereleaseIdentifier(value: object): value is PrereleaseIdentifier {
  return true;
}

export function PrereleaseIdentifierFromJSON(json: any): PrereleaseIdentifier {
  return PrereleaseIdentifierFromJSONTyped(json, false);
}

export function PrereleaseIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrereleaseIdentifier {
  if (json == null) {
    return json;
  }
  return {

    'value': json['value'] == null ? undefined : json['value'],
    'numericValue': json['numericValue'] == null ? undefined : BigIntegerFromJSON(json['numericValue']),
  };
}

export function PrereleaseIdentifierToJSON(json: any): PrereleaseIdentifier {
  return PrereleaseIdentifierToJSONTyped(json, false);
}

export function PrereleaseIdentifierToJSONTyped(value?: PrereleaseIdentifier | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {

    'value': value['value'],
    'numericValue': BigIntegerToJSON(value['numericValue']),
  };
}

