/* tslint:disable */
/* eslint-disable */
//@ts-nocheck
/**
 * Unreal Plugin Manager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents the location of a source, containing information about its URL and associated SHA hash.
 * @export
 * @interface SourceLocation
 */
export interface SourceLocation {
  /**
   * Gets or sets the URL representing the location of the source.
   * @type {string}
   * @memberof SourceLocation
   */
  url: string;
  /**
   * Gets or sets the SHA hash associated with the source location.
   * @type {string}
   * @memberof SourceLocation
   */
  sha: string;
}

/**
 * Check if a given object implements the SourceLocation interface.
 */
export function instanceOfSourceLocation(value: object): value is SourceLocation {
  if (!('url' in value) || value['url'] === undefined) return false;
  if (!('sha' in value) || value['sha'] === undefined) return false;
  return true;
}

export function SourceLocationFromJSON(json: any): SourceLocation {
  return SourceLocationFromJSONTyped(json, false);
}

export function SourceLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceLocation {
  if (json == null) {
    return json;
  }
  return {

    'url': json['url'],
    'sha': json['sha'],
  };
}

export function SourceLocationToJSON(json: any): SourceLocation {
  return SourceLocationToJSONTyped(json, false);
}

export function SourceLocationToJSONTyped(value?: SourceLocation | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {

    'url': value['url'],
    'sha': value['sha'],
  };
}

