/* tslint:disable */
/* eslint-disable */
//@ts-nocheck
/**
 * Unreal Plugin Manager API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents information about a source patch file, including its filename
 * and content.
 * @export
 * @interface SourcePatchInfo
 */
export interface SourcePatchInfo {
  /**
   *
   * @type {string}
   * @memberof SourcePatchInfo
   */
  filename?: string;
  /**
   *
   * @type {string}
   * @memberof SourcePatchInfo
   */
  content?: string;
}

/**
 * Check if a given object implements the SourcePatchInfo interface.
 */
export function instanceOfSourcePatchInfo(value: object): value is SourcePatchInfo {
  return true;
}

export function SourcePatchInfoFromJSON(json: any): SourcePatchInfo {
  return SourcePatchInfoFromJSONTyped(json, false);
}

export function SourcePatchInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourcePatchInfo {
  if (json == null) {
    return json;
  }
  return {

    'filename': json['filename'] == null ? undefined : json['filename'],
    'content': json['content'] == null ? undefined : json['content'],
  };
}

export function SourcePatchInfoToJSON(json: any): SourcePatchInfo {
  return SourcePatchInfoToJSONTyped(json, false);
}

export function SourcePatchInfoToJSONTyped(value?: SourcePatchInfo | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {

    'filename': value['filename'],
    'content': value['content'],
  };
}

